Add FAQ which can be managed through bot commands
RLBot/discord-bot pull request #24
Opened 2021-05-09 16:54 UTC by NicEastvillage

This PR adds the ability to manage an FAQ channel through commands. This allows us to have a FAQ channel with a streamlined format and where everyone can adjust/update/add if needed. Rearranging questions is also easy. The following commands are added:
* `faq_channel <#channel_id>` : Sets the FAQ channel. Will probably only be used once.
* `add_faq <question> <answer>` : Appends a question to the list of FAQs
* `edit_faq <qid> <question> <answer>` : Updates question `qid` to the given question and answer
* `swap_faqs <qid1> <qid2>` : Swaps question `qid1` and `qid2`
* `del_faq <qid>` : Removes question `qid`

This is how it will look like:
![billede](https://user-images.githubusercontent.com/21122471/117580336-c98ffe80-b0f7-11eb-8460-6a51126f83cb.png)

2021-05-09 18:00 UTC, VirxEC commented
This looks cool - even if we decide not to have an FAQ, having this tool in the bot will still be nice.

2021-05-09 18:40 UTC, skyborgff requested changes
Also remove the binary RLBotDiscordBot/cogs/__pycache__/admin.cpython-37.pyc

I'll test it later and approve after the changes

2021-05-09 18:40 UTC, skyborgff commented on RLBotDiscordBot/cogs/faq.py
> +            print("hi1")
Remove debug prints :P

2021-05-09 18:40 UTC, skyborgff commented on RLBotDiscordBot/cogs/faq.py
> +            print("hi2")
Remove debug prints :P V2

2021-05-16 10:14 UTC, skyborgff approved these changes
Looks good :)

2021-05-16 10:34 UTC, merged